SELECT YEAR(EA.DIFFERENTIATION_DATE) AS YEAR, 
    (SELECT MAX(EDA.SIZE_OF_COLONY)
     FROM ECOLI_DATA AS EDA
     WHERE YEAR(EDA.DIFFERENTIATION_DATE) = YEAR
    ) - EA.SIZE_OF_COLONY AS YEAR_DEV, EA.ID
FROM ECOLI_DATA AS EA
ORDER BY YEAR, YEAR_DEV
